sealsystems/node-ipp

lib/attributes.js

For `Get-Notifications` the `notify-sequence-numbers` must be part of the request.

Add notify-sequence-numbers

---

package.json

fix: Trigger release

---

lib/serializer.js
lib/statusCodes.js

Add client-error-not-fetchable error code for IPP Infrastructure Printer

fix: Add client-error-not-fetchable error code

---

lib/parser.js
test/lib/parserTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

chore: Fixed error parsing CUPS operations

---

lib/parser.js

Hey @seal-mt 😊 
Hey @seal-mis 😊 
As announced in Slack, here is the PR that fixed the strange behavior that HP printers handle IPP differently when it comes to attributes that have a language flag set.
Could you please review this, and if you are fine with this, squash / merge it?

Fix HP printer compatibility.

---

lib/serializer.js

Hey @seal-mis 😊 
Hey @seal-mt 😊 
As discussed on Slack we (i.e., @yeldiRium and I) propose a file change here to silently ignore unknown groups and attributes in IPP messages.
Could you please review our changes, and squash / merge them if you are fine with them?

Ignore unknown groups and attributes.

---

README.md
lib/parser.js
lib/serializer.js
test/lib/parserTest.js

Fixed error parsing CUPS operations
Fix HP printer compatibility.
Ignore unknown groups and attributes.
<details>
<summary>
</summary>
<p> …

fix: Fixed bugs

---

lib/attributes.js

Added attribute 'notify-wait'
<details>
<summary>
</summary>
<p>
- `WIP:`
It is highly recommended to open a pull request as soon as …

fix: Added attribute 'notify-wait'

---

lib/attributes.js
lib/serializer.js

Add attributes for event notifications.
Write group 'event-notification-attributes-tag'

fix: Notify missings

---

README.md

See also https://jira.sealsystems.de/jira/browse/
<details><summary>Click here for a detailed introduction. Please read before submitting your first pull request!</summary>
<p>
- `WIP:`
It is …

feat: Included SEAL Systems specific operation attributes

---

README.md
lib/enums.js
lib/parser.js
lib/printer.js
lib/request.js
package-lock.json
package.json
test/lib/printerTest.js
test/lib/requestTest.js

See also https://jira.sealsystems.de/jira/browse/
<details><summary>Click here for a detailed introduction. Please read before submitting your first pull request!</summary>
<p>
- `WIP:`
It is …

feat: Enabled streaming of ipp response

---

lib/request.js
package-lock.json
package.json

See also https://jira.sealsystems.de/jira/browse/
<details><summary>Click here for a detailed introduction. Please read before submitting your first pull request!</summary>
<p>
- `WIP:`
It is …

feat: timeout for waiting on response

---

lib/attributes.js
lib/printer.js
lib/request.js

- `feat:`
1. timeout option add to printer option
2. add job attributes `print-scaling`
- `fix:`
catch parse exception, add them to error callback

add attributes `print-scaling`,fix timeout handle, and catch parse exception

---

lib/printer.js
test/lib/printerTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

chore: Use url protocol as default for uri

---

README.md

<details>
<summary>
</summary>
<p>
- `WIP:` …

Remove badges from README.md

---

lib/attributes.js
test/lib/serializerTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

chore: added attrribute print-scaling

---

README.md
lib/printer.js
package-lock.json
package.json
test/lib/printerTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

feat: Added http(s) agent as option

---

lib/printer.js
lib/request.js
package-lock.json
package.json

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: Propagate error from input to output stream

---

lib/printer.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: Fix missing response in execute

---

.github/workflows/release.yml

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: Use different token for releasing

---

package.json

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: Fix package.json

---

README.md

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: trigger build

---

.github/workflows/release.yml
package.json

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: next try fixing build

---

README.md
lib/printer.js
lib/request.js
package-lock.json
package.json
test/lib/requestTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

feat: Added options for socket timeout

---

lib/request.js
test/lib/requestTest.js

<details>
<summary>
</summary>
<p>
- `WIP:` …

fix: Fixed bug at socket close timeout
